modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/p1ut0nium-git/Rough-Mobs-Revamped/issues"

[[mods]]
modId="roughmobsrevamped"
version="${version}"
displayName="Rough Mobs Revamped"
updateJSONURL="https://github.com/p1ut0nium-git/Rough-Mobs-Revamped/blob/1.14.4/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rough-mobs-revamped"
logoFile="examplemod.png"
credits="Thanks to Lellson8 for open sourcing his original mod: Rough Mobs 2"
authors="p1ut0nium_94"
description='''
A continuation of the orginal Rough Mobs 2 mod by Lellson. This mod makes normal Minecraft monsters harder by adding equipment, special abilities, and bosses.
'''

[[dependencies.roughmobsrevamped]]
modId="forge" #mandatory
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.roughmobsrevamped]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"